export enum SCREENS {
	ENTRANCE = "Entrance",
	GAME_MAP = "GameMap"
}

export enum TEAM {
	WHITE = "white",
	RED = "red",
	BLUE = "blue"
}
export enum COLORS {
	N_WHITE = "#FFFFFF",
	D_WHITE = "#D7CCB9",
	L_RED = "#E54E4E",
	N_RED = "#EFEAE1",
	D_RED = "#C13030",
	DD_RED = "#8F1919",
	L_BLUE = "#6B81CE",
	N_BLUE = "#42569C",
	D_BLUE = "#25295C",
	DD_BLUE = "#101337",
	L_BROWN = "#BEA47E",
	D_BROWN = "#C69D61",
	DD_BROWN = "#7B6442",
	DDD_BROWN = "#654F2F",
	N_BROWN = "#DCB680",
	N_BLACK = "#000000"
}

export enum ActionTypes {
	RESET_SESSION_STORE = "RESET_SESSION_STORE",
	PUSH_SCREEN = "PUSH_SCREEN",

	GET_TEAM_INFO_REQUEST = "GET_TEAM_INFO_REQUEST",
	GET_TEAM_INFO_SUCCESS = "GET_TEAM_INFO_SUCCESS",
	GET_TEAM_INFO_FAILURE = "GET_TEAM_INFO_FAILURE",

	CONNECT_TO_SOCKET_REQUEST = "CONNECT_TO_SOCKET_REQUEST",
	CONNECT_TO_SOCKET_SUCCESS = "CONNECT_TO_SOCKET_SUCCESS",
	CONNECT_TO_SOCKET_FAILURE = "CONNECT_TO_SOCKET_FAILURE",

	SEND_INVITE_CODE_REQUEST = "SEND_INVITE_CODE_REQUEST",
	SEND_INVITE_CODE_SUCCESS = "SEND_INVITE_CODE_SUCCESS",
	SEND_INVITE_CODE_FAILURE = "SEND_INVITE_CODE_FAILURE",

	HANDLE_GAME_STATUS = "HANDLE_GAME_STATUS"
}
